name: pangeo
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - xarray
  - bokeh
  - cartopy
  - dask
  - distributed
  - dill
  - dask-kubernetes
  - gcsfs
  - geopandas
  - intake::intake-xarray
  - zarr
  - nbconvert
  - matplotlib
  - ipympl
  - ipython
  - numcodecs
  - python-blosc
  - lz4
  - nomkl
  - nbserverproxy
  - jupyter
  - jupyterlab=0.35
  - jupyterlab_launcher
  - jupyter_client
  - ipywidgets
  - graphviz
  - nodejs
  - satpy
  - imageio
  - imageio-ffmpeg
  - rasterio
  - geoviews
  - networkx
  - numba
  - palettable
  - pysal
  - scikit-learn
  - seaborn
  - statsmodels
  - xlrd
  - xlsxwriter
  - pip:
    - kubernetes
    - graphviz
    - cenpy==1.0.0rc2
    - contextily
    - rasterstats
    - libpysal
    - geopy
    - mplleaflet
    - mapclassify
    - esda
